name = "ItuRPropagation"
uuid = "a73e506c-35e8-47b2-857c-dfce7ead1349"
authors = ["Hillary Kchao <hillary.kchao@gmail.com>", "Alberto Mengali <disberd@gmail.com>"]
repo = "https://github.com/disberd/ItuRPropagation.jl"
version = "0.3.0-DEV"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
UnitfulExt = "Unitful"

[compat]
Artifacts = "1"
Unitful = "1.23.0"
julia = "1.10"
