name = "ItuRPropagation"
uuid = "a73e506c-35e8-47b2-857c-dfce7ead1349"
authors = ["Hillary Kchao <hillary.kchao@gmail.com>", "Alberto Mengali <disberd@gmail.com>"]
repo = "https://github.com/disberd/ItuRPropagation.jl"
version = "0.3.0-DEV"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
Artifacts = "1"
DelimitedFiles = "1.9.1"
julia = "1.10"
